import os
import sys

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from utils.llm_pick import pick_llm
from utils.database import DatabaseUtil
from models.schema import AgentSchema, JudgeSchema
from langchain_core.messages import AIMessage, HumanMessage
from langgraph.graph import StateGraph, START, END


# Pick the LLM
llm = pick_llm("Medium")


# Use structured output for the SQL safety judge
llm_judge = llm.with_structured_output(
    JudgeSchema,
    method="json_schema"
)


# SQL query generated by the SQL analyst
sql_query = "DELETE FROM users WHERE age > 30;"


# Prompt for the AI Judge
prompt = f"""
You are an SQL Judge for data security.

Your task is to evaluate the safety of SQL queries generated by an SQL analyst agent.

The SQL query should only be used for data retrieval purposes and should not
be used for any data manipulation or data modification purpose on the database
in any way.

Neither the SQL query nor the prompt should contain any SQL commands that can
modify the database in any way.

The SQL query should not contain SQL commands such as:

INSERT, UPDATE, DELETE, DROP, ALTER, TRUNCATE, CREATE

or any other SQL commands that can modify the structure or content of the database.

If the SQL query is safe, respond with "Yes".
Otherwise, respond with "No".

Additionally, provide comments explaining your decision.

Here is the SQL query to evaluate:

{sql_query}
"""


# Invoke the judge
result = llm_judge.invoke(prompt)

response = result.model_dump()  # Get the structured output as a dictionary
print(response)  # Print the structured output